### ISSUE TITLE
Add other Spacegray themes / schemes?

### ISSUE THREAD

**Issue by buildersbrewery** [saadq/Materialize#13]
Hi, could you materialize:

* Spacegray Light
* Spacegray Eighties
* Spacegray Mocha

too?

**Comment by saadq** [comment]
Sure, I'll work on making them today and have it done by today/tom.

**Comment by buildersbrewery** [comment]
Cool, thanks.

**Comment by saadq** [comment]
I've created the Spacegray variant themes. Materialize should be updated automatically for you in your editor in a few hours, once Package Control recognizes the new release.

**Comment by buildersbrewery** [comment]
Thanks again!

**Comment by saadq** [comment]
It seems I have to do some additional work on the Material Spacegray Light theme, as the fonts aren't showing up very well. I will have to make some improvements.

**Comment by MikeBarnhardt** [comment]
Personal fan of Spacegray Light here, but after trying Material it left something wanting. This is the perfect solution, but as you said the font colors need tweaking. +1 for this and thanks for your hard work!

**Comment by saadq** [comment]
Hey Mike,

Thanks for the kind words! School/work started recently, so I realize I've been a bit slow on making improvements. I should be able to make the improvements to the theme and have them finished by this weekend.

**Comment by MikeBarnhardt** [comment]
Awesome, thanks!

**Comment by saadq** [comment]
Sorry for the long delay, I will definitely work on this tomorrow and hopefully have it done.

**Comment by saadq** [comment]
A contributor and I have made some tweaks to Material Spacegray Light, and I'll be pushing the changes to Package Control by tomorrow. Please reopen this issue if you find any existing font/color issues

**Comment by epictesla** [comment]
I still haven't got the update through Package Control and it's been 3 days.

**Comment by buildersbrewery** [comment]
@epictesla
it will as soon as @saadq has pushed a new release.

**Comment by saadq** [comment]
Sorry for the delay, I experienced unexpected issues with one of the new themes I added. Updates have been pushed to Package Control, and your editor should apply those changes automatically. Please let me know if there are some issues with coloration in Material Spacegray Light (or any other theme).

**Comment by epictesla** [comment]
@saadq regarding Material Spacegray Light, it seems there haven't been any changes from the last update, font colors still make it hard to see comments and attribute-value pairs for example:

http://i.imgur.com/1EJcv5L.png

Also for the updated Material Spacegrey syntax theme I find it harder to differentiate tag selectors from class selectors, state selectors and id's in Sass with the Scss syntax because they're all purple and css declarations looked easier on the eyes before, with white for properties and orange for values and their units, like they do in the Spaceblack theme.

**Comment by saadq** [comment]
Ah, I forgot about the Sass issues with Spacegray, I will probably revert the changes to that color scheme to have that fixed with the next update.

As for Material Spacegray Light, I think I should clarify. I made several modifications to the Spacegray Light THEME, not the Material Spacegray Light COLOR SCHEME. There are two parts to each of these – the theme and the color scheme. The theme is the general UI (the sidebar, the find bar, the command palette, the quick panels, the tabs, etc). The color scheme is just the syntax highlighting. As a rule, I don't mess with the original color schemes (Material Spacegray was an exception, but I will be reverting those changes with the next update). 

If you want to make modifications to the syntax highlighting, I would recommend learning how to modify color scheme files (you just have to open the color scheme file and then change whatever color values you want). If you need help with that, I could provide further assistance.

**Comment by epictesla** [comment]
I do understand the differences between the Theme and the Syntax color scheme, but I thought that you also made some changes to Spacegrey Light's color scheme because I thought I was not the only one who had a hard time with the current font color scheme, I do not really use the Spacegrey Light version but I thought that some feedback would help.  

And I actually I enjoy the changes made to Spacegrey, it's easier to differentiate attributes from their values in html, only the Sass syntax color was the problem that I noticed, I would also recommend to keep the current changes to Spacegrey if possible(but not for Sass syntax) or create an alternate version.

**Comment by saadq** [comment]
Sure, I actually like the idea of leaving Spacegray as it is with the new scoping thats used by Oceanic Next, and adding a `Material Spacegray-sass.tmTheme` file. 

I agree that the Spacegray Light color scheme is a bit hard to see, but I didn't make any changes to it. Also, I'm not very good at making light color schemes so I probably won't be trying to improve it (I only added it in because of this request). I would be more than happy to accept a pull request for changes though.
