### ISSUE TITLE
Show bottom panel separator

### ISSUE THREAD

**Issue by epictesla** [saadq/Materialize#15]
Hi there and thank you for your  devotion on improving this theme.

I would be pretty grateful if you could manage to implement the following option "material_theme_panel_separator", while the Material Theme comes with it, it would be a pretty nice addition for those who like some contrast, as it seems it doesn't work when activated in the user preferences settings.

**Comment by saadq** [comment]
Hey @epictesla,

This seems like it was an addition put in recently by the original Material Theme. I'll make sure it is compatible with my versions of the theme, and then I'll try to implement the functionality.

**Comment by epictesla** [comment]
Oh well, I wasn't aware of that, no worries then and if I may ask what other differences are between your version and the original Material Theme besides the added color schemes(which is a very nice addition)?

**Comment by saadq** [comment]
There isn't all that much difference. When I create a new Material theme, like Material Spacegray for example, I do the following steps:

* I create a specialized [.sublime-theme](https://github.com/saadq/Materialize/blob/master/Material%20Spacegray.sublime-theme) and [.tmTheme](https://github.com/saadq/Materialize/blob/master/schemes/Material%20Spacegray.tmTheme) file for the color scheme
* I create a [widgets](https://github.com/saadq/Materialize/tree/master/widgets/spacegray) folder and [assets](https://github.com/saadq/Materialize/tree/master/assets/spacegray) folder for the particular theme and customize the files inside
* I recolor a lot of the files inside the assets folder in photoshop (this is probably what takes the most time)

The main difference is the .sublime-theme files. That is where I load the assets, and I do it a bit differently than the original Material theme because of the different folder structures, which is why I have to make sure the panel separator will work.

**Comment by epictesla** [comment]
Hey you might want to look out for this too:

[issue#407](https://github.com/equinusocio/material-theme/issues/407)

And I must say I really like the way your version is going and appreciate the effort and also would you consider donations to keep up the motivation?

**Comment by saadq** [comment]
Thanks for the kind words! I may be considering the donations route once summer is over because of work and school, but for now I have time to make improvements easily. 

And nice, I can't wait to see what it looks like with the separator on the sidebar. 

For now, the bottom separator seems to be working fine for my themes. I will most likely have to recolor them for a few themes that are already really dark like Seti, but for most of the rest it should be working fine.

**Comment by epictesla** [comment]
Seems that Material Theme got updated, I'll just leave this here as a reminder for you when you get some time to update your version too, thanks and have a nice day.

**Comment by saadq** [comment]
Thanks for keeping me updated. There seem to have been several updates to Material Theme, but it doesn't seem like he has added in the Sidebar separator yet.

**Comment by epictesla** [comment]
Well to be honest I didn't even try the theme, I only have your version installed but on the sidebar separator issue #407 the issue author left a comment today saying that it was "nice" supposing he was referring to the latest updates so I tought that the feature was added, but again I didn't checked so I'm sorry for that.

**Comment by saadq** [comment]
I think I'm going to close this issue for now, feel free to reopen it if you see the sidebar option get added in. I'll try to keep a lookout for it too.
