### ISSUE TITLE
Arrow key buttons to scroll tabs and button to show list of all tabs look weird.

### ISSUE THREAD

**Issue by mindstormer12** [saadq/Materialize#27]
http://imagizer.imageshack.com/img907/6774/A20ZHo.png

Not sure if this is intended, but as you can see, the arrow key buttons to scroll tabs and button to show list of all tabs look weird. They are black and don't fit the rest of the solarized dark theme.

On another note, would you consider this a fork of the equinusocio's material-theme? Does it update along with that theme?

**Comment by saadq** [comment]
I apologize for the long delay in my response. Are you still facing this issue? If so, what theme/color scheme are you using?

This project started off as a fork in equinusocio's material-theme, but it has drifted pretty significantly from his in it's implementation so I would consider them two different projects now. I try to keep track of the changes he makes on his so that I can bring it to Materialize.

**Comment by mindstormer12** [comment]
It seems to look properly now, closing this issue.
