### ISSUE TITLE
Add support for the App Bar

### ISSUE THREAD

**Issue by jrappen** [saadq/Materialize#36]
compare [equinusocio/material-theme-appbar](https://github.com/equinusocio/material-theme-appbar)

```json
"material_theme_tree_headings": true
```

**Comment by saadq** [comment]
Hmm, going to hold off on this. There wouldn't be any way to do this without creating another package on Package Control called **Materialize App Bar** or something. I had to do something similar for the White Panels, and one of the maintainers of Package Control was a bit reluctant to allow my package in since the names were so similar and there existed something already quite like it.

If there is any more demand for this feature, it's something I can look into adding though.

**Comment by mrmartineau** [comment]
:+1: for this feature :smile:

**Comment by amucinom** [comment]
:+1: as well :grin:

**Comment by saadq** [comment]
hmmm

**Comment by pineapplethief** [comment]
+1 for this

**Comment by saadq** [comment]
I've made a [Reddit post](https://www.reddit.com/r/SublimeText/comments/43pvaw/how_many_of_you_use_the_material_theme_appbar/) about this issue to see the interest, I'm starting to lean towards porting it.

**Comment by saadq** [comment]
Pull Request has been sent to Package Control: https://github.com/wbond/package_control_channel/pull/5285

**Comment by saadq** [comment]
Good news guys, the pull request has been merged! :)

You can now install `Materialize-Appbar` through Package Control and the Appbar should automatically appear after you restart your editor. The appbar supports the theme's accent colors, so here's what it would look like if we use Material Augmented Reaction and have `material_theme_accent_red: true` in our settings:

<img width="1392" alt="screen shot 2016-03-11 at 1 01 16 pm" src="https://cloud.githubusercontent.com/assets/5678694/13710978/2ebed598-e78a-11e5-9235-a8dcc77a4616.png">

And you can use the option `material_theme_tree_headings` to get headings in your sidebar:

<img width="1392" alt="screen shot 2016-03-11 at 1 08 33 pm" src="https://cloud.githubusercontent.com/assets/5678694/13711014/6063b456-e78a-11e5-90e1-c19329dc9edc.png">

Please reopen the issue if you find anything wrong with the Appbar!
