### ISSUE TITLE
Facebook Colorscheme 

### ISSUE THREAD

**Issue by ssang** [saadq/Materialize#44]
Are there any plans to Materialize the Facebook theme?

https://github.com/mbixby/facebook-color-scheme

**Comment by saadq** [comment]
I believe there is already a [Facebook Material Theme](https://packagecontrol.io/packages/Facebook%20Material%20Theme). Are you unhappy with that one?

**Comment by ssang** [comment]
Unfortunately it seems to break any time I try to install it. The last
update has been quite a while ago, maybe something changed during that
time. You've got the best hybrids so thought I'd request if it's possible.

**Comment by saadq** [comment]
Oh, you're right it appears to be broken. It looks like he changed the root folder name which messed up all the paths to his assets. I'm going to try to contact him, and see if he replies. Otherwise, I wouldn't mind creating a version for it. Although he doesn't seem to have any contact information, so that might be an issue.

**Comment by ssang** [comment]
That's great! I'll be waiting patiently! Thanks for your hard work!!

**Comment by saadq** [comment]
I've finished the theme, but I just want to get permission from the creator of the Facebook color scheme to make sure it's okay since he didn't specify a LICENSE.

<img width="1392" alt="screen shot 2016-03-10 at 10 38 57 pm" src="https://cloud.githubusercontent.com/assets/5678694/13692598/09943f02-e711-11e5-81a2-d2b2dbfc3758.png">

**Comment by mbixby** [comment]
> Hey Michael,
> 
> I’m the creator of a Sublime Text package called Materialize (https://github.com/saadq/Materialize) which is basically a mixture of the popular Material Theme and some popular color schemes for Sublime Text. I recently received a request to make a material version for your Facebook color scheme (https://github.com/saadq/Materialize/issues/44), but your LICENSE still says TBA so I wanted to check with you to see if it was okay to port it. I would definitely be giving you credits in the README if you do allow it. Let me know!
> 
> Regards,
> Saad
> 

I added an open source license but I don’t support the effort. One of the motivations behind the scheme and accompanying themes was drawing the right amount of attention to various interface components – and notably not polluting the theme with graphical artefacts that draw attention needlessly. As I look at Materialize, I don’t think it fits that idea based on how I use code editors. For example, fuzzy search should be preffered to folder navigator which should make the navigator panel subdued – in the above screenshot, it looks more significant than code itself, full of colors. The vibrant green on icons and active file and folders overpowers anything else on the screen.

It kind of saddens me to see the screenshot with the color scheme highlighting every language keyword possible. Since publishing I've made own edits into the scheme and various tmLanguage files to prevent it. [Github Notes](https://github.com/mbixby/github-notes-color-scheme) and [Bluebird](https://github.com/mbixby/bluebird) mention mantras like:
> deference and clarity
> provide relaxed, calm atmosphere for reading and writing code
> sharp, tasteful interface with focus on content

I’m also biased against the almighty Material Design, there’s a lot of decisions that don’t make sense to me.

Hopefully I’ll find the time to put some more work into the scheme since I finished school and all, I’d certainly like to fix the bugs and further the ideas behind it, at least for my own usage.

**Comment by saadq** [comment]
Thanks for your feedback! I appreciate you posting your thoughts on this, and adding an open-source license. While I respect your opinion, I'll still be adding the theme to meet this request. However, @ssang, I would definitely urge you to check out the original Facebook theme as a lot of his points are valid and may be more desirable. 

I'll be pushing out the changes today.

**Comment by saadq** [comment]
Material Facebook has been added. Your theme will automatically update once Package Control recognizes the changes.
