### ISSUE TITLE
Smaller search panel

### ISSUE THREAD

**Issue by Code-Curious** [saadq/Materialize#52]
An option for a smaller search panel would be great. Compared to some other themes like Numix, this theme's search panel is considerably bigger, which can be annoying on a small laptop screen.

**Comment by saadq** [comment]
This may be a bit tricky due to the assets used with the input fields. I've been trying to keep these themes as consistent with [Material Theme](https://github.com/equinusocio/material-theme) as possible, so it might be a better idea for you to raise an issue there. If the original creator does decide to add an option for customizing the search panel, I'd be happy to port the changes to Materialize as well, though as I've said, I'm a bit doubtful.

**Comment by gj1118** [comment]
The original material theme already has this option. 
```"material_theme_compact_panel"            : true ,```

Please see the snapshot below.
![image](https://cloud.githubusercontent.com/assets/473101/13910064/e089b6f2-eef2-11e5-93fa-a665759a3a29.png)

**Comment by saadq** [comment]
Oh it looks like he just added the feature 5 days ago. I'll port it soon.

**Comment by gj1118** [comment]
Thanks

**Comment by saadq** [comment]
This feature has been added, your themes should update shortly. Please reopen the issue if there are any problems with the new `material_theme_compact_panel` feature.
