### ISSUE TITLE
Theme Firewatch

### ISSUE THREAD

**Issue by tudorchira** [saadq/Materialize#67]
Theme Name: Firewatch
Link to the color scheme: https://github.com/paradox41/firewatch-color-scheme

Thanks in advance!

**Comment by saadq** [comment]
Hey @tudorchira, thanks for the theme request. Next time, be sure to fill out all the relevant details:

-Theme Name
**-Author Name**
-Link to the color scheme
**-License of color scheme**

Don't worry about it for this one though.

**Comment by saadq** [comment]
Just finished the theme, I'll have it pushed to Package Control by tomorrow.

<img width="1392" alt="screen shot 2016-05-31 at 2 40 52 pm" src="https://cloud.githubusercontent.com/assets/5678694/15686314/b7cb3758-273d-11e6-9f77-2f758b2e40ea.png">

**Comment by tudorchira** [comment]
Sorry for not submitting the full credentials. 
The theme looks grear, thanks!

**Comment by saadq** [comment]
I forgot to comment on this, but I pushed the changes to Package Control and Materialize should have automatically updated for you. Feel free to reopen this if there are any issues!

**Comment by jk779** [comment]
@tudorchira can you elaborate the differences to flatland? it looks very similar to me? :) Anyways, great job again @saadq 💯

**Comment by tudorchira** [comment]
@jk779 I never really used Flatland in the past but I did a quick comparison and the differences seem pretty clear to me, the colors are quite different - even if the background color is somewhat similar.

**Comment by saadq** [comment]
Hey @jk779, thanks for your comment. The main purpose of doing these theme requests is to create a version of the original [Material Theme](https://github.com/equinusocio/material-theme) that matches a person's desired color scheme perfectly – I don't design new/different themes for each request (otherwise I wouldn't be able to do these requests!). 

Let's say @tudorchira wanted to use the Firewatch color scheme and tried to use Flatland theme alongside with it. This is what it would look like:

<img width="1392" alt="screen shot 2016-06-02 at 11 07 50 am" src="https://cloud.githubusercontent.com/assets/5678694/15749922/484de81e-28b2-11e6-9fc0-ba5cf43399d7.png">

I think the main reason people like Material Theme is because of how flat everything looks and the minimal contrast, which is why I think there is a point in making a theme that does match it perfectly like so:

<img width="1392" alt="screen shot 2016-06-02 at 11 24 12 am" src="https://cloud.githubusercontent.com/assets/5678694/15750467/9137741c-28b4-11e6-8e42-c017051780a6.png">

Sorry if I was misleading in any way.
