### ISSUE TITLE
Broken since latest version (3127)

### ISSUE THREAD

**Issue by kud** [saadq/Materialize#84]
- material_theme_accent_xxx doesn't work anymore, you can't change the colour
- no more file icons

<img width="230" alt="image" src="https://cloud.githubusercontent.com/assets/655838/24948367/5853d336-1f6a-11e7-98ef-78afa8324960.png">

<img width="231" alt="image" src="https://cloud.githubusercontent.com/assets/655838/24948537/eb7494ac-1f6a-11e7-902e-58fc713de4df.png">

_should be default material theme colour and icons viewable_

**Comment by saadq** [comment]
Thanks for the report, I'll look into it.

**Comment by ValentinCreative** [comment]
Same problem here

**Comment by saadq** [comment]
Okay, so Build 3127 had a lot of UI changes that might have triggered this to happen.

This seemed to fix the issue for me:

1. Switch to some other non-Materialize theme
2. Switch back to the Materialize theme
3. Restart Sublime (If not fixed already)

This seemed to revert the theme back to its normal state. Can you guys try it and let me know if it works?

**Comment by kud** [comment]
It seems that they roll back: https://www.sublimetext.com/3

I brew cask uninstall sublime-text-dev and brew cask install it and when I click on "update", there's no update.

3127 isn't available anymore apparently. So I can't try.

**Comment by kud** [comment]
You can find it via https://download.sublimetext.com/Sublime%20Text%20Build%203127.dmg but there's also https://download.sublimetext.com/Sublime%20Text%20Build%203128.dmg apparently.

**Comment by kud** [comment]
I'll be back on this issue when homebrew will update `sublime-text-dev`. As I reinstalled it via brew cask, it installed 3126 (so stable version) and I don't have any update for the moment.

I'm too lazy to update sublime-text-dev cask task to put the latest version, and I don't want to install it manually. So when I'll be back on dev channel, i'll come back here to say if it works or not. Thanks for your comprehension :D

**Comment by saadq** [comment]
Np, just let me know whenever.

**Comment by kud** [comment]
Thank you very much for your answer, your time, and your excellent sublime text theme. ;)

By the way, there's a new new update: https://www.sublimetext.com/3dev 3128

**Comment by kud** [comment]
It often takes more time to explain than doing it: https://github.com/caskroom/homebrew-versions/pull/3620

**Comment by lucsky** [comment]
Same here, the accent color preference is ignored but I do get file icons. Changing to a non material theme and back does not fix the problem.

**Comment by saadq** [comment]
Hmm, accents + file icons seem to be fine for me on Build 3128. Let me detail my exact steps in case there was some nuance in what I did that may have fixed it:

1. In Command Palette, type `UI: Select Theme` and then I switched to `Material Theme` (not Materialize, this is the original Material Theme)

2. Do `UI: Select Theme` again and switch back to a Materialize theme (`Material Spacegray` for example).

3. Restart Sublime

4. Check that file icons are working and adding something like `material_theme_accent_red: true` works.

---

@lucsky If following the above steps didn't fix it for you, would you mind providing the following info:

1. Are you on build 3127 or 3128?
2. Are you using the `Materialize-White-Panels` or `Materialize-Appbar` plugins?
3. If restarting Sublime didn't fix anything, could you also try uninstalling `Materialize`, reinstalling it, switching to a Materialize theme with the `UI: Select Theme` and then restarting Sublime and check if there are any issues.

**Comment by lucsky** [comment]
@saadq: I did all the steps and yes file icons are working for me but the `material_theme_accent_[whatever]: true` is ignored and appear to be "stuck" with indigo as shown in @kud screenshot.

1. I am on build 3128
2. I do use Materialize-Appbar but it doesn't seem to have any impact, I get the same problem without it.
3. I did uninstall, reinstall and restart it several times but it is still "stuck" with the indigo accent.

**Comment by saadq** [comment]
Okay I've been investigating a bit and this issue seems very strange... I'm not entirely sure what the cause is right now but I'm currently working on trying to get a permanent solution. For now, I think I have a working fix although it is kind of strange:

1. Uninstall `Materialize` as well as `Material Theme` if you have it installed.
2. Install **BOTH** `Materialize` and `Material Theme`.
3. Do `UI: Select Theme` and choose `Material-Theme.sublime-theme`.
4. Do `UI: Select Color Scheme` and choose `Material-Theme`.
5. **Restart Sublime**.
6. At this point, things get a little funky. Your editor might currently look like this:

![screen shot 2017-04-12 at 12 24 49 pm](https://cloud.githubusercontent.com/assets/5678694/24968420/2d96bfa8-1f7b-11e7-97d4-d8bf5ecd6ce6.png)

As you can see, some files have their icons, and some files don't. For any file that is not displaying the file icon, just hover your cursor over it and the file icon should appear next to it.

7. Do `UI: Select Theme` and choose a Materialize theme (Example: `Material Spacegray.sublime-theme`)
8. Do `UI: Select Color Scheme` and choose a Materialize color scheme (Example: `Material Spacegray`)
9. Restart Sublime for good measure.

At this point, the Materialize theme should not have any of the weird accent overrides and file icons should be showing.

---

This is a TEMPORARY workaround. I know it's a bit much, but I'm looking into a better solution (or hopefully another Sublime build is released that fixes whatever breaking changes occurred here).

Please let me know if the above still doesn't work for you.

**Comment by lucsky** [comment]
@saadq : yup, that made it work, I'm back to where I was before the update to 3128 including with the AppBar addon. Thanks !

**Comment by kud** [comment]
It didn't work for me. I did it twice.

Plus, `$ subl .` doesn't work anymore here, so I come back to 3126. :/

**Comment by saadq** [comment]
@kud So both file icons and accents are still screwed up for you?

Just to check, if you use `Material-Theme` as your theme, does it work fine or is it messed up as well?

**Comment by kud** [comment]
Okay, I did a fresh install of Sublime Text + removed my preferences and put it back, now, everything is ok.

I think what I missed was Material Theme which asked you to install "A File Icon" package I didn't have.

Everything's fine, or even better because I've got beautiful icons now.

<img width="720" alt="image" src="https://cloud.githubusercontent.com/assets/655838/24997151/efd9a3ae-2035-11e7-83ad-22c8915edc4f.png">

**Comment by kud** [comment]
https://github.com/ihodev/a-file-icon is clearly needed I think.

**Comment by kud** [comment]
Okay, I understand more and more now.

If you have some icons troubles, remove "a file icon" or "zzz a file icon zzz" and reinstall it if you want it (or not, if you want classic icons).

**Comment by kud** [comment]
By the way, why do we have to install `Material-Theme`?

Materialize doesn't provide colour scheme but also theme?

**Comment by saadq** [comment]
I'm not entirely sure, but Materialize and Material Theme had drifted a bit from each other, and I need to finish the rework so that they are much more alike. The icons they had been using were the same, but it looks like since then Material Theme switched to using the package that is mentioned above. I will probably do something similar. Thanks for the info @kud.

**Comment by saadq** [comment]
Update: It looks like as of Build 3131, you won't have to deal with this workaround, everything should be working fine (try reinstalling Materialize in case it isn't). This means you don't have to keep the Material Theme installed. It's still recommended that you install the [A File Icon](https://github.com/ihodev/a-file-icon) package as their icons look better, and I will probably make installing them a prereq to installing Materialize (similar to what Material Theme does) soon.

**Comment by kud** [comment]
+1 for "A File icon".
