### ISSUE TITLE
Theme breaks after installing SublimeGit?

### ISSUE THREAD

**Issue by rockethouse** [saadq/Materialize#9]
Not sure if the issue being caused by this theme, but I've been using it just fine for the past month and since installing SublimeGit (https://sublimegit.net/) yesterday and reloading it, the theme broke and I had to re-setup my user file... it had reverted back to the default theme.

Has anyone else experienced this?

**Comment by saadq** [comment]
Hm... I just installed SublimeGit and restarted Sublime, but I wasn't able to recreate your problem. What OS are you on? Also, could you try uninstalling the theme and reinstalling it?

**Comment by rockethouse** [comment]
Damn, must be just me or my setup! that's cool... It's only happened twice now, If it happens again I will investigate further and maybe post a screenshot of whats happening (it's a weird one!)

Feel free to close this for now.

I'm using OSX 10.10

**Comment by saadq** [comment]
Yeah, please take a screenshot of any weird things that happen to the theme. I'm thinking it may just be the graphical corruption that happens when the theme automatically updates (you usually just have to restart Sublime and it would get fixed). I'm going to close the issue for now, but please reopen it and comment if my assumption is wrong.
